name: TruffleHog Secret Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, develop ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Nécessaire pour que TruffleHog analyse tout l'historique

      - name: Install TruffleHog
        run: |
          pip install truffleHog

      - name: Run TruffleHog scan
        run: |
          trufflehog git file://$GITHUB_WORKSPACE --since-commit HEAD~20 --json > trufflehog-report.json
          if [ -s trufflehog-report.json ]; then
            echo "⚠️ Secrets found!"
            cat trufflehog-report.json
            exit 1
          fi
